addons:
    apt:
        packages:
            - autoconf
            - automake
            - autopoint
            - gettext
            - libasound2-dev
            - libavcodec-dev
            - libavformat-dev
            - libavutil-dev
            - libexpat1-dev
            - libflac++-dev
            - libgtk2.0-dev
            - libid3tag0-dev
            - libjack-dev
            - libmad0-dev
            - libmp3lame-dev
            - libogg-dev
            - libsndfile1-dev
            - libsoxr-dev
            - libvorbis-dev
            - portaudio19-dev
            - vamp-plugin-sdk
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libportsmf-dev libsoundtouch-dev libtwolame-dev libwxgtk3.0-dev
    - git show -s --format="wxT(\"<a href=\\\"http://github.com/audacity/audacity/commit/%H\\\">%h</a> of %cd\")" | tee ./src/RevisionIdent.h
    - FLAGS="-Wall -Wextra"
    - export CFLAGS="$CFLAGS $FLAGS"
    - export CXXFLAGS="$CXXFLAGS $FLAGS"
dist: trusty
sudo: required
language:
    - cpp
script:
    - ./bootstrap && ./configure --disable-dynamic-loading && make
